### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'v_Sur'

### ISSUE THREAD

**Issue by betegon** [wei-tim/YOWO#13]
When using the command stated in the `README` file I got the following error:

```
2020-01-28 19:01:54 training at epoch 1, lr 0.000100
Traceback (most recent call last):
  File "train.py", line 322, in <module>
    train(epoch)
  File "train.py", line 170, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/bt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/bt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/bt/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/bt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/bt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bt/Desktop/YOWO/dataset.py", line 53, in __getitem__
    clip, label = load_data_detection(self.base_path, imgpath,  self.train, self.clip_duration, self.shape, self.dataset_use, jitter, hue, saturation, exposure)
  File "/home/bt/Desktop/YOWO/clip.py", line 161, in load_data_detection
    im_ind = int(im_split[num_parts-1][0:5])
ValueError: invalid literal for int() with base 10: 'v_Flo'
```

**Do you have any idea why this occur?**

I have been digging into the code and I just can't get it to work. I understand the error itself, but not its origin.

Thank you for your time.

**Comment by okankop** [comment]
Hi @betegon, this line of code "im_ind = int(im_split[num_parts-1][0:5])" reads the image index from the image path. Could you please check if "im_split[num_parts-1][0:5]" is really the image path.

**Comment by betegon** [comment]
Hi @okankop , thanks a lot for answering back that quickly.
That's really the issue, if `im_split[num_parts-1][0:5]` is the path (string), how will you cast it into an integer? 
There will be always the same error as   what you are doing here `im_ind = int(im_split[num_parts-1][0:5])` is casting an string into a integer.

**Comment by okankop** [comment]
Please use the annotation files shared in the README. Then it will return the index of the frame.

**Comment by betegon** [comment]
Thank you, I was trying to train it with folder `labels` from UCF4 instead of your annotations in the `README`.

For future reference, this is the **setup that allowed me to train it**:

## Command
```bash
$ python train.py --dataset ucf101-24  --data_cfg cfg/ucf24.data  --cfg_file cfg/ucf24.cfg --n_classes 24 --backbone_3d resnext101  --backbone_3d_weights weights/resnext-101-kinetics.pth --backbone_2d darknet --backbone_2d_weights weights/yolo.weights
```

## Project structure 
This shows only level 2 depth into YOWO, below there is more information
```bash
YOWO
├── backbones_2d
│   └── darknet.py
├── backbones_3d
│   ├── mobilenet.py
│   ├── mobilenetv2.py
│   ├── resnet.py
│   ├── resnext.py
│   ├── shufflenet.py
│   └── shufflenetv2.py
├── backup
├── cfam.py
├── cfg
│   ├── jhmdb21.cfg
│   ├── jhmdb21.data
│   ├── test.cfg
│   ├── test.data
│   ├── ucf24.cfg
│   ├── ucf24.data
│   └── yolo.cfg
├── cfg.py
├── clip.py
├── data
│   ├── coco.names
│   ├── jhmdb21.names
│   ├── ucf24.names
│   └── voc.names
├── dataset.py
├── eval_results.py
├── evaluation
│   └── Object-Detection-Metrics
├── examples
│   ├── biking.gif
│   ├── brush_hair.gif
│   ├── catch.gif
│   ├── fencing.gif
│   ├── golf_swing.gif
│   └── pull_up.gif
├── finalAnnots.mat
├── FocalLoss.py
├── model.py
├── opts.py
├── Pretrained Models.zip
├── README.md
├── region_loss.py
├── run_jhmdb-21.sh
├── run_ucf101-24.sh
├── run_video_mAP_jhmdb.sh
├── run_video_mAP_ucf.sh
├── train.py
├── ucf24
│   ├── brox-images
│   ├── fastOF-images
│   ├── groundtruths_ucf
│   ├── labels
│   ├── rgb-images
│   ├── splitfiles
│   ├── testlist.txt
│   ├── train_data
│   └── trainlist.txt
├── utils.py
├── video_mAP.py
└── weights
    ├── resnext-101-kinetics.pth
    └── yolo.weights
``` 
in `ucf24/groundtruths_ucf` there are the annotations downloaded from `README`:
```bash
BasketballDunk_v_BasketballDunk_g01_c01_00033.txt
BasketballDunk_v_BasketballDunk_g01_c01_00033.txt
BasketballDunk_v_BasketballDunk_g01_c01_00035.txt
.
.
.
```
