### ISSUE TITLE
Cannot start training

### ISSUE THREAD

**Issue by ken292** [wei-tim/YOWO#15]
Thank you very much for sharing your research!
I am trying to follow your README.md and want to do training.
But I have this error. I am guessing maybe I have different version of library?
I am really sorry to disturb you, but could you please give me some help?

`2020-02-05 21:44:41 training at epoch 1, lr 0.000100
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Thesis\Master\YOWO-master\train.py", line 322, in <module>
    train(epoch)
  File "F:\Thesis\Master\YOWO-master\train.py", line 170, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\ProgramData\Anaconda3\envs\yowo_1\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.`

**Comment by ken292** [comment]
This is the list of my library, just in case it might be helpful

![image](https://user-images.githubusercontent.com/58810041/73848153-885ccf00-4862-11ea-9426-545562d87a88.png)

**Comment by okankop** [comment]
Hi @ken292, I believe you are trying to run the code on Windows. Please refer to this thread to resolve your issue: https://github.com/pytorch/pytorch/issues/5858

**Comment by ken292** [comment]
Hi @okankop, Thank you very much for the quick reply.
I am going to read it first

**Comment by ken292** [comment]
@okankop Hi, I am really sorry, but I am a bit lost. This is my first time trying. Could you please help assist me on what should I do or check?
I am really sorry if this is troublesome

**Comment by ken292** [comment]
Problem solved,
thank you @okankop

**Comment by Th3OnlyN00b** [comment]
but what did you do to solve it? I'm trying to find a tutorial for this on Windows.

**Comment by ken292** [comment]
@Th3OnlyN00b the easiest way is to make num_workers = 0
it is around line 58 in train.py

once you have done that, you should be fine.
Good luck!
