### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by lrhjw** [wei-tim/YOWO#20]
when i train the ucf24,it occurred,can you give me some advice? thank you
Traceback (most recent call last):
  File "train.py", line 322, in <module>
    train(epoch)
  File "train.py", line 180, in train
    loss = region_loss(output, target)
  File "/home/zc/anaconda3/envs/torch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zc/coode/YOWO/region_loss.py", line 230, in forward
    nH, nW, self.noobject_scale, self.object_scale, self.thresh, self.seen)
  File "/home/zc/coode/YOWO/region_loss.py", line 127, in build_targets
    iou = bbox_iou(gt_box, pred_box, x1y1x2y2=False) # best_iou
  File "/home/zc/coode/YOWO/utils.py", line 74, in bbox_iou
    cw = w1 + w2 - uw
RuntimeError: Expected object of type torch.DoubleTensor but found type torch.FloatTensor for argument #3 'other'

**Comment by 17854224426** [comment]
@lrhjw 
Hi，
I also have this problem, how do you solve it
