### ISSUE TITLE
Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed

### ISSUE THREAD

**Issue by nkise** [wei-tim/YOWO#38]
Wanted to reduce num of classes to 8 but after starting train have this error.

```
void THCudaTensor_scatterFillKernel(TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, Real, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [0,0,0], thread: [1,0,0] Assertion `indexValue >= 0 && indexValue < tensor.sizes[dim]` failed.
Traceback (most recent call last):
  File "train.py", line 329, in <module>
    train(epoch)
  File "train.py", line 180, in train
    loss = region_loss(output, target)
  File "/home/nkise/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nkise/Documents/neuron/YOWO/region_loss.py", line 259, in forward
    loss_cls = self.class_scale * FL(cls, tcls)
  File "/home/nkise/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nkise/Documents/neuron/YOWO/FocalLoss.py", line 58, in forward
    self.alpha = self.alpha.cuda()
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by nkise** [comment]
@wei-tim it seems that you have hardcoded numbers of class in `region_loss.py`

```
        # try focal loss with gamma = 2
        FL = FocalLoss(class_num=24, gamma=2, size_average=False)
        loss_cls = self.class_scale * FL(cls, tcls)
```

**Comment by wei-tim** [comment]
@nkise 
Hi,
that's true, you need to modify this part if you train with your own dataset.

**Comment by nkise** [comment]
> @nkise
> Hi,
> that's true, you need to modify this part if you train with your own dataset.

So, as I understand, I need to modify `clues_num` to my number of classes?

**Comment by wei-tim** [comment]
@nkise 

exactly.

**Comment by hfarhid** [comment]
Did this fix you problem? still have same issue after fixing the class_num

**Comment by okankop** [comment]
Currently I am refactoring the whole repo. So, there won't be these kind of bugs. More importantly, I will add the training details for the AVA dataset, and also update the article with AVA results. 

Stay tuned!
