### ISSUE TITLE
Change clip size

### ISSUE THREAD

**Issue by kinivi** [wei-tim/YOWO#41]
Hi,
I have an Error while changing a clip_size in cfg:
`RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 4 and 5 at /opt/conda/conda-bld/pytorch_1579040055865/work/aten/src/THC/generic/THCTensorMath.cu:62`

Is there any other configuration that I need to edit?
Thank You

**Comment by kinivi** [comment]
Full-stack trace:
```
Traceback (most recent call last):
  File "train.py", line 334, in <module>
    train(epoch)
  File "train.py", line 183, in train
    output = model(data)
  File "/home/nkise/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nkise/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/nkise/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nkise/Documents/neuron/FluRecog/model.py", line 87, in forward
    x = torch.cat((x_3d, x_2d), dim=1)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 4 and 5 at /opt/conda/conda-bld/pytorch_1579040055865/work/aten/src/THC/generic/THCTensorMath.cu:62
```

**Comment by LIUHAO121** [comment]
if you change the clip size,the dims of conv3D results will change,you need use torch.mean(conv3d_out,dim=2) to reduce the dims of 3d results
