### ISSUE TITLE
video_mAP

### ISSUE THREAD

**Issue by west-i** [wei-tim/YOWO#42]
1.When I want to calculate video_map, I did not find the testlist_video.txt file. 

2.I generated one myself, the format in it is like  walk/50_FIRST_DATES_walk_f_cm_np1_le_med_33，it can run begin, but with the following error：

 iou is:  0.05
Traceback (most recent call last):
  File "video_mAP.py", line 327, in <module>
    video_mAP_jhmdb()
  File "video_mAP.py", line 320, in video_mAP_jhmdb
    print(evaluate_videoAP(gt_videos, detected_boxes, CLASSES, iou_th, True))
  File "/home/chase/YOWO/eval_results.py", line 244, in evaluate_videoAP
    ap = video_ap_one_class(gt, pred_cls, iou_thresh, bTemporal, cls_len)
  File "/home/chase/YOWO/eval_results.py", line 155, in video_ap_one_class
    iou = np.array([iou3dt(np.array(g), boxes[:, :5]) for g in gt_this])
  File "/home/chase/YOWO/eval_results.py", line 155, in <listcomp>
    iou = np.array([iou3dt(np.array(g), boxes[:, :5]) for g in gt_this])
  File "/home/chase/YOWO/utils.py", line 195, in iou3dt
    return iou3d( b1[np.where(b1[:,0]==tmin)[0][0]:np.where(b1[:,0]==tmax)[0][0]+1,:] , b2[np.where(b2[:,0]==tmin)[0][0]:np.where(b2[:,0]==tmax)[0][0]+1,:]  ) * temporal_inter / temporal_union
  File "/home/chase/YOWO/utils.py", line 184, in iou3d
    assert b1.shape[0] == b2.shape[0]
AssertionError

**Comment by Holmes-GU** [comment]
Have you reproduce the reported results in the paper?

**Comment by Holmes-GU** [comment]
> 1.When I want to calculate video_map, I did not find the testlist_video.txt file.
> 
> 2.I generated one myself, the format in it is like walk/50_FIRST_DATES_walk_f_cm_np1_le_med_33，it can run begin, but with the following error：
> 
> iou is: 0.05
> Traceback (most recent call last):
> File "video_mAP.py", line 327, in 
> video_mAP_jhmdb()
> File "video_mAP.py", line 320, in video_mAP_jhmdb
> print(evaluate_videoAP(gt_videos, detected_boxes, CLASSES, iou_th, True))
> File "/home/chase/YOWO/eval_results.py", line 244, in evaluate_videoAP
> ap = video_ap_one_class(gt, pred_cls, iou_thresh, bTemporal, cls_len)
> File "/home/chase/YOWO/eval_results.py", line 155, in video_ap_one_class
> iou = np.array([iou3dt(np.array(g), boxes[:, :5]) for g in gt_this])
> File "/home/chase/YOWO/eval_results.py", line 155, in 
> iou = np.array([iou3dt(np.array(g), boxes[:, :5]) for g in gt_this])
> File "/home/chase/YOWO/utils.py", line 195, in iou3dt
> return iou3d( b1[np.where(b1[:,0]==tmin)[0][0]:np.where(b1[:,0]==tmax)[0][0]+1,:] , b2[np.where(b2[:,0]==tmin)[0][0]:np.where(b2[:,0]==tmax)[0][0]+1,:] ) * temporal_inter / temporal_union
> File "/home/chase/YOWO/utils.py", line 184, in iou3d
> assert b1.shape[0] == b2.shape[0]
> AssertionError

Have reproduced the reported results in the paper?

**Comment by Griffintaur** [comment]
I am also getting the following error. I try running the video map for Jhmdb with the provided pretrained jhmdb model but its throwing the following error?
I will appreciate your help on this.
`
 

> File "video_mAP.py", line 338, in <module>
>     video_mAP_jhmdb()
>   File "video_mAP.py", line 331, in video_mAP_jhmdb
>     print(evaluate_videoAP(gt_videos, detected_boxes, CLASSES, iou_th, True))
>   File "YOWO/core/eval_results.py", line 250, in evaluate_videoAP
>     ap = video_ap_one_class(gt, pred_cls, iou_thresh, bTemporal, cls_len)
>   File "YOWO/core/eval_results.py", line 161, in video_ap_one_class
>     iou = np.array([iou3dt(np.array(g), boxes[:, :5]) for g in gt_this])
>   File "YOWO/core/eval_results.py", line 161, in <listcomp>
>     iou = np.array([iou3dt(np.array(g), boxes[:, :5]) for g in gt_this])
>   File "YOWO/core/utils.py", line 198, in iou3dt
>     tmin = max(b1[0,0], b2[0,0])
> IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

`

**Comment by bamaolalala** [comment]
Have you solved the problem ？
