### ISSUE TITLE
Training YOWO on a custom dataset

### ISSUE THREAD

**Issue by mohsen-gh** [wei-tim/YOWO#87]
Hi. 
Thank you for sharing the code. 
I want to train YOWO on a custom dataset. How do I prepare a custom dataset to be used for the training of YOWO?
I know that I need to extract video frames and have annotation files, but I don't know the structure of the directory of dataset contents and the structure of annotation files.

**Comment by muchlisam17** [comment]
Me too! I always get stuck when prepare custom datasets for the training of YOWO.

This issue https://github.com/wei-tim/YOWO/issues/79 didn't help me much because I faced many errors when making custom dataset preparation like AssertionError

This is one of my error from many errors I'm facing

```
[[ '/content/gdrive/MyDrive/Project/TAYOWO/dataset/Taekwondo/Frame/Momtong_Jireugi_1/Momtong_Jireugi_036_mp4-00026.jpg']]
['Ap_Koobi_1', 'Arae_Makki_1', 'Dollyeo_Chagi_1', 'Momtong_Jireugi_1']
['yowo_val_v1.2.csv']
/content/gdrive/MyDrive/Project/TAYOWO/dataset/Taekwondo/Annotation/yowo_val_v1.2.csv
{}
0
4
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/Project/TAYOWO/Coding/main.py", line 89, in <module>
    test_dataset  = Ava(cfg, split='val', only_detection=False)
  File "/content/gdrive/MyDrive/Project/TAYOWO/Coding/datasets/ava_dataset.py", line 53, in __init__
    self._load_data(cfg)
  File "/content/gdrive/MyDrive/Project/TAYOWO/Coding/datasets/ava_dataset.py", line 80, in _load_data
    assert len(boxes_and_labels) == len(self._image_paths)
AssertionError
```
